name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build Console Projects
      run: |
        dotnet build ConsoleTeleBotClient/ConsoleTeleBot.csproj --configuration Release
        dotnet build ConsoleMock/ConsoleMock.csproj --configuration Release

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Electron Globally
      run: npm install electron -g

    - name: Install Electron.NET CLI
      run: dotnet tool install ElectronNET.CLI -g

    - name: Build Electron.Net + Blazor Project for Windows
      if: matrix.os == 'windows-latest'
      run: |
        cd ConsoleTeleBotWizard
        dotnet electronize build /target win
