name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build Console Projects
      run: |
        dotnet build ConsoleTeleBotClient/ConsoleTeleBot.csproj --configuration Release
        dotnet build ConsoleMock/ConsoleMock.csproj --configuration Release

    - name: Upload Console build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myapp-console
        path: path/to/your/console/build/files

    - name: Install Electron.NET CLI
      run: dotnet tool install ElectronNET.CLI -g

    - name: Build Electron.Net + Blazor Project for Windows
      if: matrix.os == 'windows-latest'
      run: |
        cd ConsoleTeleBotWizard
        electronize build /target win /PublishReadyToRun false

    - name: Build Electron.Net + Blazor Project for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ConsoleTeleBotWizard
        dotnet restore
        electronize build /target linux /PublishReadyToRun false
      
    - name: Build Electron.Net + Blazor Project for macOS
      if: matrix.os == 'macos-latest'
      run: |
        cd ConsoleTeleBotWizard
        dotnet restore
        electronize build /target osx /PublishReadyToRun false
      
